[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs=1000

[invarient]
runs=1000
depth=1000
fail_on_revert=false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
